name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Solo se ejecuta manualmente desde GitHub

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Select TF var-file by branch
        run: |
          echo "TFVARS=dev.tfvars" >> $GITHUB_ENV  # o test.tfvars / prod.tfvars

      - name: Terraform Init
        run: terraform init
        working-directory: .infra/terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=${{ env.TFVARS }}
        working-directory: .infra/terraform
